RFC implementation
JuliaCI/LocalCoverage.jl pull request #30
Opened 2022-08-19 03:50 UTC by gabriel-ss

We are starting to integrate Julia in the company I work, and we needed a tool akin to python's [coverage report](https://coverage.readthedocs.io/en/6.4.4/cmd.html#cmd-report). LocalCoverage provided most of the functionality that we wanted, but lacked the ability to display uncovered lines, so I implemented it. We thought that the functionality might be useful for other people and decided to open a PR, with the new feature:
![image](https://user-images.githubusercontent.com/26633512/185535897-d6da6471-7dad-4bd7-ab77-12dc5f2cdc02.png)

When I went to open the PR I found the #18 and decided to work on it. This PR is my implementation proposal; I tried to respect use case described in #28 and the QoL features proposed in https://github.com/JuliaCI/LocalCoverage.jl/issues/18#issuecomment-818708330, while trying to stay close to what was described. I also removed the XML generation function since it was just a wrapper around lcov_cobertura and wasn't included in the RFC, but I can re-add it if that wasn't the intention. Lastly, I added some convenience features to facilitate use in shell scripts, e.g.

```bash
julia --project -e'using LocalCoverage; report(target_coverage=90)'
```

If there is interest in this implementation, but it somehow deviates too much from the current vision for the package, please let me know what I can do to accommodate it.

2022-08-19 12:46 UTC, tpapp requested changes

2022-08-19 12:46 UTC, tpapp commented on src/LocalCoverage.jl
> +export generate_coverage, report, html_coverage
`report` may be too general to export unconditionally, what about `report_coverage`?

2022-08-19 12:46 UTC, tpapp commented on src/LocalCoverage.jl
> +    filename::String
Please document fields.

2022-08-19 12:46 UTC, tpapp commented on src/LocalCoverage.jl
> +    package_dir::String
Please document fields.

2022-08-19 12:46 UTC, tpapp commented on src/LocalCoverage.jl
> +struct FileCoverageSummary
```suggestion
Base.@kwdef struct FileCoverageSummary
```

2022-08-19 12:46 UTC, tpapp commented on src/LocalCoverage.jl
> +struct PackageCoverage
```suggestion
Base.@kwdef struct PackageCoverage
```

2022-08-19 12:46 UTC, tpapp commented on src/LocalCoverage.jl
> +    PackageCoverage(
I would suggest using a keyword constructor. (post-1.6 non-redundant syntax is fine).

2022-08-19 12:47 UTC, tpapp commented
I only had time for a superficial review now, but it looks great, thanks for the very clean code. Feel free to depend on Julia 1.6 and bump versions in CI etc accordingly.

2022-08-20 18:53 UTC, gabriel-ss commented
Done! Let me know if more changes are needed.

2022-08-21 13:42 UTC, tpapp commented on src/LocalCoverage.jl
> -pkgdir(m::Module) = joinpath(dirname(pathof(m)), "..")
Why was this removed? Using modules should be possible (if package if already loaded).

2022-08-21 13:43 UTC, tpapp commented on src/LocalCoverage.jl
> +pkgdir(pkgstr::AbstractString) = abspath(joinpath(dirname(Base.find_package(pkgstr)), ".."))
I am fine with this for now but it is very likely to be fragile, cf https://discourse.julialang.org/t/path-of-this-package/16401/21.

2022-08-21 13:47 UTC, tpapp commented on src/LocalCoverage.jl
> +    last_line = length(coverage)
```suggestion
    i, last_line = firstindex(coverage), lastindex(coverage)
```
(generalized indexing)

2022-08-21 13:48 UTC, tpapp commented on src/LocalCoverage.jl
> +Evaluate the ranges of lines without coverage.
```suggestion
Evaluate the ranges of lines without coverage.

`coverage` is the vector of coverage counts for each line.
```

2022-08-21 13:59 UTC, tpapp requested changes
Thanks for the updates, I had a chance to read through this now. It is very nice, just asked for a couple of minor things.

The path handling mechanism is still hacky, but that is outside the scope of this PR, so I opened #31.

2022-08-21 13:59 UTC, tpapp commented on src/LocalCoverage.jl
> +format_line(summary) = hcat(
please use `function format_line ... end` for long functions.

2022-08-21 13:59 UTC, tpapp commented on src/LocalCoverage.jl
> +            strip(read(`git rev-parse --abbrev-ref HEAD`, String))
Any chance we could use [LibGit2](https://docs.julialang.org/en/v1/stdlib/LibGit2/) for this query?

2022-08-21 13:59 UTC, tpapp commented on test/runtests.jl
>  end
A trivial test for `find_gaps` would be nice.

2022-08-21 15:06 UTC, gabriel-ss commented on src/LocalCoverage.jl
> -pkgdir(m::Module) = joinpath(dirname(pathof(m)), "..")
Pkg.test doesn't have an overload for modules:
```julia
julia> Pkg.test(LocalCoverage)
ERROR: MethodError: no method matching test(::Module)
Closest candidates are:
  test(; name, uuid, version, url, rev, path, mode, subdir, kwargs...) at /usr/share/julia/stdlib/v1.8/Pkg/src/API.jl:162
  test(::Union{AbstractString, Pkg.Types.PackageSpec}; kwargs...) at /usr/share/julia/stdlib/v1.8/Pkg/src/API.jl:143
  test(::Vector{<:AbstractString}; kwargs...) at /usr/share/julia/stdlib/v1.8/Pkg/src/API.jl:144
```

2022-08-21 15:10 UTC, gabriel-ss commented on src/LocalCoverage.jl
> +pkgdir(pkgstr::AbstractString) = abspath(joinpath(dirname(Base.find_package(pkgstr)), ".."))
I don't think there is a public API for finding package names currently, but yeah, I don't like this solution either.

2022-08-21 15:14 UTC, gabriel-ss commented on src/LocalCoverage.jl
> +    last_line = length(coverage)
Nice one

2022-08-21 16:09 UTC, gabriel-ss commented on src/LocalCoverage.jl
> +            strip(read(`git rev-parse --abbrev-ref HEAD`, String))
Sure! c1bc763

2022-08-21 16:09 UTC, gabriel-ss commented on test/runtests.jl
>  end
Added in 8012b7d

2022-08-21 16:22 UTC, gabriel-ss commented on src/LocalCoverage.jl
> +format_line(summary) = hcat(
Refactored format_line in c1bc763. I think it was the longest one using the shorter syntax, but let me know if there are any other functions that you'd like to be refactored as well.

2022-08-21 16:30 UTC, gabriel-ss commented
I think that covers everything, let me know if you would prefer 007c2c6 to be reverted.

2022-08-26 09:48 UTC, merged