Show relative filenames in coverage table
JuliaCI/LocalCoverage.jl pull request #38
Opened 2022-09-08 18:42 UTC by goerz

This makes the table significantly more readable.

See https://github.com/JuliaCI/LocalCoverage.jl/issues/36#issuecomment-1240357696 Item 1

I took the liberty of refactoring the `format_line` function slightly for better readability and debuggability, and as a better starting point for "Item 2" of customizing the table output.

2022-09-09 08:30 UTC, tpapp requested changes
Great, minor changes requested.

2022-09-09 08:30 UTC, tpapp commented on src/LocalCoverage.jl
> +    name = (summary isa PackageCoverage ? "TOTAL" : relpath(summary.filename))
I don't think we should rely on the user not changing the current directory, so `package_dir` should be passed explicitly to `format_line` and then `relpath`.

2022-09-09 08:30 UTC, tpapp commented on src/LocalCoverage.jl
> +    return hcat(name, lines_hit, coverage, gaps)
Given that all arguments are strings, would something like
```suggestion
    return [name, lines_hit, coverage, gaps]
```
be sufficient?

2022-09-09 08:30 UTC, tpapp commented on test/runtests.jl
> +    println(table)
It's great that you print the result so it shows up in CI output.

2022-09-11 03:34 UTC, goerz commented on src/LocalCoverage.jl
> +    name = (summary isa PackageCoverage ? "TOTAL" : relpath(summary.filename))
I'm not sure I'd necessarily always want to show the path relative to the `package_dir`. In fact, I do have a use case where I'd prefer the path relative to the current working directory: For the [JuliaQuantumControl organization](https://github.com/JuliaQuantumControl) I have a bunch of packages that get developed simultaneously. I've set up an [organization "Dev Environment"](https://github.com/JuliaQuantumControl/JuliaQuantumControl) with a `Makefile` for working on the `master` branch of all packages in the organization in parallel. So if I'm in the main `JuliaQuantumControl` folder, I can do `make testall` which will run the test suite (with coverage) for all the org packages which are in subfolders. So I'll get reports like

```
┌─────────────────────────────────────────────────┬────────┬────────┬────────┬──────────┐
│ File name                                       │  Total │    Hit │ Missed │ Coverage │
├─────────────────────────────────────────────────┼────────┼────────┼────────┼──────────┤
│ QuantumControlBase.jl/src/QuantumControlBase.jl │      1 │      1 │      0 │     100% │
│ QuantumControlBase.jl/src/conditionalthreads.jl │      0 │      0 │      0 │        - │
│ QuantumControlBase.jl/src/functionals.jl        │    138 │    138 │      0 │     100% │
│ QuantumControlBase.jl/src/gradgen.jl            │    166 │    132 │     34 │      80% │
│ QuantumControlBase.jl/src/infohook.jl           │     12 │     11 │      1 │      92% │
│ QuantumControlBase.jl/src/liouvillian.jl        │     55 │     51 │      4 │      93% │
│ QuantumControlBase.jl/src/objectives.jl         │     51 │     47 │      4 │      92% │
│ QuantumControlBase.jl/src/optimize.jl           │     74 │     49 │     25 │      66% │
│ QuantumControlBase.jl/src/propagate.jl          │     24 │      0 │     24 │       0% │
│ QuantumControlBase.jl/src/saving.jl             │     23 │      0 │     23 │       0% │
│ QuantumControlBase.jl/src/shapes.jl             │     28 │     27 │      1 │      96% │
│ QuantumControlBase.jl/src/testutils.jl          │    208 │    124 │     84 │      60% │
│ QuantumControlBase.jl/src/weyl_chamber.jl       │     73 │     71 │      2 │      97% │
├─────────────────────────────────────────────────┼────────┼────────┼────────┼──────────┤
│ TOTAL                                           │    853 │    651 │    202 │      76% │
└─────────────────────────────────────────────────┴────────┴────────┴────────┴──────────┘
```

which is nice, because I can scroll through and immediately see which package that reports belongs to. But I can also `cd` into the the `QuantumControlBase.jl` subfolder and run `make test` there, and get just

```
┌───────────────────────────┬────────┬────────┬────────┬──────────┐
│ File name                 │  Total │    Hit │ Missed │ Coverage │
├───────────────────────────┼────────┼────────┼────────┼──────────┤
│ src/QuantumControlBase.jl │      1 │      1 │      0 │     100% │
│ src/conditionalthreads.jl │      3 │      3 │      0 │     100% │
│ src/functionals.jl        │    138 │    138 │      0 │     100% │
│ src/gradgen.jl            │    168 │    136 │     32 │      81% │
│ src/infohook.jl           │     12 │     12 │      0 │     100% │
│ src/liouvillian.jl        │     55 │     51 │      4 │      93% │
│ src/objectives.jl         │     51 │     47 │      4 │      92% │
│ src/optimize.jl           │     74 │     65 │      9 │      88% │
│ src/propagate.jl          │     24 │     19 │      5 │      79% │
│ src/saving.jl             │     24 │     23 │      1 │      96% │
│ src/shapes.jl             │     28 │     27 │      1 │      96% │
│ src/testutils.jl          │    208 │    124 │     84 │      60% │
│ src/weyl_chamber.jl       │     73 │     71 │      2 │      97% │
├───────────────────────────┼────────┼────────┼────────┼──────────┤
│ TOTAL                     │    859 │    717 │    142 │      83% │
└───────────────────────────┴────────┴────────┴────────┴──────────┘
```

2022-09-11 04:14 UTC, goerz commented on src/LocalCoverage.jl
> +    return hcat(name, lines_hit, coverage, gaps)
It would have to be `[name lines_hit coverage gaps]`, that is, a 1×4 matrix. I just tested it with the vector version (with commas), and that would give a `LoadError: The number of columns in the header must be equal to that of the table.`

I don't know, I'm always feeling a bit weird about Julia's matrix syntax, so I'd have a slightly preference for `hcat`, but I'm ok with whatever you prefer.

2022-09-12 10:18 UTC, tpapp commented on src/LocalCoverage.jl
> +    return hcat(name, lines_hit, coverage, gaps)
You can just use NamedTuples as rows, see #39.

2022-09-13 07:58 UTC, tpapp commented
Contained in #39.

2022-09-13 07:58 UTC, closed without merging