WIP - Naive implementation of LCOV -> Cobertura conversion
JuliaCI/LocalCoverage.jl pull request #42
Opened 2023-01-19 12:25 UTC by BambOoxX

- Not tested inside the package (tests fail for some reason ?)
- Comments are welcome

2023-01-19 13:42 UTC, tpapp requested changes
Please revert all the superfluous spacing changes, then I will review again. CI actually passes, just code coverage fails, please add some tests (eg a file you convert and check results).

2023-01-19 13:42 UTC, tpapp commented on src/LocalCoverage.jl
> +        gaps=is_pkg ? "" : format_gaps(summary))
Please revert spaces around `=`, that's the style we use in this package (common style guides recommend spaces around operators).

2023-01-19 13:42 UTC, tpapp commented on src/LocalCoverage.jl
> +            foreground=:red,
ditto

2023-01-19 13:42 UTC, tpapp commented on src/LocalCoverage.jl
> +        Highlighter((data, i, j) -> j == percentage_column && row_coverage[i] >= 90, foreground=:green),
ditto

2023-01-19 13:42 UTC, tpapp commented on src/LocalCoverage.jl
> +        body_hlines=[length(rows) - 1]
ditto

2023-01-19 13:42 UTC, tpapp commented on src/LocalCoverage.jl
> +        lines_hit = lines_tracked - sum(length, coverage_gaps; init=0)
ditto

2023-01-19 13:42 UTC, tpapp commented on src/LocalCoverage.jl
> +    lines_tracked = sum(x -> x.lines_tracked, files; init=0)
ditto

2023-01-19 13:42 UTC, tpapp commented on src/LocalCoverage.jl
> +function convert(lcov::LcovCobertura)
please do not pun on function names in `Base`, rename this, eg `convert_lcov_to_xml`

2023-01-19 13:55 UTC, BambOoxX commented on src/LocalCoverage.jl
> +        gaps=is_pkg ? "" : format_gaps(summary))
Sorry about that, I actually use the VSCode extension and I couldn't find the settings for that.

2023-01-19 14:36 UTC, tpapp requested changes
Nice work, but I think at this point it is WIP. I will wait for it to mature and then review again in a week.

2023-01-19 14:36 UTC, tpapp commented on src/LocalCoverage.jl
> +Convert a LCOV file to a nested dictionary structure ready fr XML conversion
```suggestion
Convert a LCOV file to a nested dictionary structure ready for XML conversion
```

2023-01-19 14:36 UTC, tpapp commented on src/LocalCoverage.jl
> +function write_lcov_to_xml(xmlpath::String, lcovpath::String)
```suggestion
function write_lcov_to_xml(xmlpath::AbstractString, lcovpath::AbstractString)
```

2023-01-19 14:36 UTC, tpapp commented on src/LocalCoverage.jl
> +function lcov_parse(lcov::LcovParser; timestamp=round(Int, Dates.datetime2unix(Dates.now())))
```suggestion
function lcov_parse(lcov::LcovParser; timestamp = round(Int, Dates.datetime2unix(Dates.now())))
```

2023-01-19 14:36 UTC, tpapp commented on src/LocalCoverage.jl
> +        # TODO figure a julian way to exclude some packages, e.g. with a function as in `filter`
please keep track of the todo list in the PR description, eg with a 

- [ ] do this

list.

2023-01-19 14:36 UTC, tpapp commented on test/runtests.jl
> +
can we check something about the `xmltrace` file?

2023-01-19 14:36 UTC, tpapp commented on src/LocalCoverage.jl
> +struct LcovParser
since you use it in multiple places I think it may be useful. but please document the fields and note that it is used internally.

2023-01-19 16:03 UTC, BambOoxX commented on src/LocalCoverage.jl
> +function lcov_parse(lcov::LcovParser; timestamp=round(Int, Dates.datetime2unix(Dates.now())))
Hey Tamas, I am not sure what settings you use, but it's not the default formatting right ? I've been trying to use a `.JuliaFormmater.toml` file but it modifies a lot of stuff. Would you happen to have a specific one ?

2023-01-28 16:55 UTC, BambOoxX commented
Hey @tpapp I am not sure what I can improve about this. I solved all the main problems that were already identified. I do not see what could be improved right now, yet I'm pretty sure a lot could still be done. I you have time for suggestions, feel free to tell me.

2023-01-28 16:55 UTC, BambOoxX commented
Hey @tpapp I am not sure what I can improve about this. I solved all the main problems that were already identified. I do not see what could be improved right now, yet I'm pretty sure a lot could still be done. I you have time for suggestions, feel free to tell me.

2023-03-24 10:13 UTC, tpapp commented
I apologize, I forgot about this. Will review it next week and will most likely merge.

Thank you for the ping.

2023-03-24 16:41 UTC, tpapp commented on test/runtests.jl
> +
@BambOoxX: this is the only unaddressed comment. Even a trivial check (eg reading the header and checking that it starts with `<?xml`, or even longer if it makes sense) would suffice.

2023-03-24 17:45 UTC, BambOoxX commented on test/runtests.jl
> +
Ah yes, I missed this. Do you think it would be relevant to implement the backwards parsing : xml to lcov? This way we could check that the round-trip works fine. Otherwise, if there is a trusted source with both files we could check that we respect the contents of both?

2023-03-25 10:08 UTC, tpapp commented on test/runtests.jl
> +write_lcov_to_xml(xmltrace,lcovtrace)
```suggestion
write_lcov_to_xml(xmltrace, lcovtrace)
open(xmltrace, "r") do io
    header = readline(io)
    doctype = readline(io)
    @test header == """<?xml version="1.0" encoding="UTF-8"?>"""
    @test startswith(doctype, "<!DOCTYPE coverage")
end
```

2023-03-25 10:09 UTC, tpapp commented on test/runtests.jl
> +
For now, something very simple would suffice, like the suggestion I made above. Just to check that the file was generated and vaguely resembles the desired output.

If you need the roundtrip functionality, it would be great for another PR. Let's keep this one simple.

2023-03-26 07:42 UTC, merged

2023-03-26 07:42 UTC, tpapp commented
Thanks!