Allow passing custom CSS file to `html_coverage`
JuliaCI/LocalCoverage.jl pull request #56
Opened 2024-07-26 08:14 UTC by jagot

I added a keyword argument to `html_coverage` that takes the path to a custom CSS file, to be used as
```Julia
html_coverage(cov, css="path/to/custom.css")
```
Using e.g. a CSS file based on the [Gruvbox](https://github.com/gruvbox-community/gruvbox) theme, it can look like

![image](https://github.com/user-attachments/assets/f49d11ce-d60c-4fec-8492-4fcdd88e8ce1)

![image](https://github.com/user-attachments/assets/817dd0c9-e839-462e-86c5-506d24ec004f)

![image](https://github.com/user-attachments/assets/54d15eb4-3183-48a9-b46a-0619877de2b2)

![image](https://github.com/user-attachments/assets/e3c693d8-3566-4e16-a780-8e1cca31861d)

[gruvbox.zip](https://github.com/user-attachments/files/16388659/gruvbox.zip)

2024-07-26 09:34 UTC, tpapp requested changes
Thanks, just requested a tiny change, and please **add a test**. It can be something trivial, eg

1. you provide a CSS file and then grep for it in the result, and

2. you provide a bogus argument (eg an integer) and it errors.

2024-07-26 09:34 UTC, tpapp commented on src/LocalCoverage.jl
> +function html_coverage(coverage::PackageCoverage; gitroot = ".", open = false, dir = tempdir(), css::Union{Nothing,String}=nothing)
```suggestion
function html_coverage(coverage::PackageCoverage; gitroot = ".", open = false, dir = tempdir(), css::Union{Nothing,AbstractString}=nothing)
```

2024-07-26 10:38 UTC, jagot commented
Thanks for the suggestions!

I added a test for the argument error you suggested, and generation of a coverage report using a dummy CSS file, testing for equality using the [FileCmp](https://github.com/jlapeyre/FileCmp.jl) package as a extra test dependency. Hope that is OK.

2024-07-27 06:44 UTC, tpapp approved these changes
Thanks for the very clean code.

2024-07-27 06:44 UTC, merged